# Site settings
baseurl = "http://clairegaulinbrown.com"
languageCode = "en-us"
theme = "hugo-artist-portfolio"
sectionPagesMenu = "main"

[params]
	name = "Your name"
	description = "Your description"
	email = "your@email.com"
	author = "Claire Gaulin-Brown"
	
