# Site settings
baseurl = ""
languageCode = "en-us"
theme = "frances"
sectionPagesMenu = "main"

[menu]

  [[menu.main]]
    identifier = "shop"
    name = "Shop"
    pre = "<i class='fa fa-heart'></i>"
    url = "https://shopclairegaulinbrown.bigcartel.com/"
    weight = 0

[params]
	name = "Claire Gaulin-Brown"
	description = "Artist and Illustrator"
	email = "gaulinbrown@gmail.com"
	author = "Claire Gaulin-Brown"
	
