# Site settings
baseurl = "http://clairegaulinbrown.com"
languageCode = "en-us"
theme = "hugo-artist-portfolio"
sectionPagesMenu = "main"

[menu]

  [[menu.main]]
    identifier = "shop"
    name = "Shop"
    pre = "<i class='fa fa-heart'></i>"
    url = "https://shop.clairegaulinbrown.com"
    weight = 0

[params]
	name = "Claire Gaulin-Broen"
	description = "Artist and Illustrator"
	email = "gaulinbrown@gmail.com"
	author = "Claire Gaulin-Brown"
	
