---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: data/artworks.toml
  label: Artworks
- type: document
  path: data/bioPhotos.toml
  label: Bio Photos
- type: document
  path: data/commissionsPhotos.toml
  label: Commissions Photos
- type: document
  path: data/illustrations.toml
  label: Illustration Clients
- type: directory
  path: content/posts
  label: Blog Posts
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: document
  path: content/about/_index.md
  label: About Page
- type: document
  path: content/commissions/_index.md
  label: Commissions Page
- type: document
  path: content/contact/_index.md
  label: Contact Page
- type: document
  path: content/illustrations/_index.md
  label: Illustration Clients Page
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: 
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: 0.55.6
